name: Sync to GitLab

on:
  push:
    branches: [ main, master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          # Kita isolasi token di sini agar terpisah dari URL utama
          GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Kita daftarkan remote URL menggunakan variabel token
          git remote add gitlab https://oauth2:${GL_TOKEN}@://gitlab.com
          
          # Lakukan push semua branch ke gitlab
          git push gitlab refs/remotes/origin/*:refs/heads/* --prune --force
